### ISSUE TITLE
Cadena de Favores

### ISSUE THREAD

**Issue by Azowyl** [TP-Foodie/Foodie-Backend#18]
El sistema otorgará la posiblidad de marcar un envío como cadena de favores. El usuario que generá el pedido deberá indicar cuantos puntos de gratitud otorgará a la persona que se encargue de realizar el delivery del pedido. Para esto el usuario deberá tener la cantidad de puntos de gratitud suficientes en su cuenta.

El usuario luego podrá cambiar los puntos de gratitud para beneficios exclusivos; como por ejemplo envíos gratis.

**Comment by herniadlf** [comment]
En lugar de hacerse como en los pedidos que el usuario selecciona un delivery, acá uno hace uno pedido como favor y queda en espera hasta que otro cliente lo "toma". Así que como usuario debería distinguirse en el mapa (pantalla principal) los pedidos que están en la zona como favor.
Luego, deberíamos tener alguna "accion" como la q tiene el pedido para "asignarse".
Por uiltimo, cuando se entregan, deben registrarse esos puntos de gratitud en favor de la persona que lo trasladó.
